export type FoodCategory =
  | "Rice"
  | "Eggs"
  | "Chicken"
  | "Fish"
  | "Milk"
  | "Curd"
  | "Oats"
  | "Fruits"
  | "Vegetables"
  | "Nuts"
  | "Seeds"
  | "Legumes"
  | "Grains"
  | "Common Indian Foods";

export type DietaryType = "vegetarian" | "non_vegetarian" | "vegan" | "eggetarian";

export type SubstitutionGroup =
  | "lean_protein"
  | "fatty_protein"
  | "complex_carb"
  | "simple_carb"
  | "plant_protein"
  | "dairy_protein"
  | "healthy_fat"
  | "vegetable";

export interface FoodItem {
  id: string;
  name: string;
  category: FoodCategory;
  servingSize: number;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  dietaryType: DietaryType;
  substitutionGroup: SubstitutionGroup;
  allergens?: string[];
  budgetTier: "budget_friendly" | "moderate" | "premium";
}

export const FOOD_DATABASE: FoodItem[] = [
  // 1. Rice & Grains
  {
    id: "food-1",
    name: "Basmati White Rice (Cooked)",
    category: "Rice",
    servingSize: 100,
    servingUnit: "g",
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-2",
    name: "Brown Rice (Cooked)",
    category: "Rice",
    servingSize: 100,
    servingUnit: "g",
    calories: 111,
    protein: 2.6,
    carbs: 23.0,
    fat: 0.9,
    fiber: 1.8,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-3",
    name: "Rolled Oats (Raw)",
    category: "Oats",
    servingSize: 50,
    servingUnit: "g",
    calories: 190,
    protein: 6.5,
    carbs: 34.0,
    fat: 3.5,
    fiber: 5.0,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-4",
    name: "Whole Wheat Roti / Chapati",
    category: "Common Indian Foods",
    servingSize: 1,
    servingUnit: "piece (40g)",
    calories: 104,
    protein: 3.2,
    carbs: 20.4,
    fat: 0.8,
    fiber: 2.8,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    allergens: ["gluten"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-5",
    name: "Cooked Quinoa",
    category: "Grains",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "premium",
  },
  {
    id: "food-6",
    name: "Steamed Idli",
    category: "Common Indian Foods",
    servingSize: 2,
    servingUnit: "pieces (100g)",
    calories: 132,
    protein: 4.0,
    carbs: 26.0,
    fat: 0.8,
    fiber: 1.5,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-7",
    name: "Plain Dosa (Homemade)",
    category: "Common Indian Foods",
    servingSize: 1,
    servingUnit: "medium (80g)",
    calories: 168,
    protein: 3.9,
    carbs: 29.0,
    fat: 3.8,
    fiber: 1.2,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },

  // 2. Chicken & Poultry
  {
    id: "food-8",
    name: "Chicken Breast (Boneless/Skinless)",
    category: "Chicken",
    servingSize: 100,
    servingUnit: "g",
    calories: 120,
    protein: 22.5,
    carbs: 0.0,
    fat: 2.6,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "lean_protein",
    budgetTier: "moderate",
  },
  {
    id: "food-9",
    name: "Grilled Chicken Breast (Cooked)",
    category: "Chicken",
    servingSize: 100,
    servingUnit: "g",
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "lean_protein",
    budgetTier: "moderate",
  },
  {
    id: "food-10",
    name: "Chicken Thigh (Skinless, Cooked)",
    category: "Chicken",
    servingSize: 100,
    servingUnit: "g",
    calories: 209,
    protein: 26.0,
    carbs: 0.0,
    fat: 10.9,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "fatty_protein",
    budgetTier: "moderate",
  },

  // 3. Eggs
  {
    id: "food-11",
    name: "Whole Large Egg (Boiled/Raw)",
    category: "Eggs",
    servingSize: 1,
    servingUnit: "egg (50g)",
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    fiber: 0.0,
    dietaryType: "eggetarian",
    substitutionGroup: "fatty_protein",
    allergens: ["eggs"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-12",
    name: "Liquid Egg Whites",
    category: "Eggs",
    servingSize: 100,
    servingUnit: "ml (~3 egg whites)",
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    dietaryType: "eggetarian",
    substitutionGroup: "lean_protein",
    allergens: ["eggs"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-13",
    name: "Egg Omelette (2 Eggs, 1 tsp oil)",
    category: "Eggs",
    servingSize: 1,
    servingUnit: "serving (110g)",
    calories: 184,
    protein: 12.6,
    carbs: 1.0,
    fat: 14.2,
    fiber: 0.0,
    dietaryType: "eggetarian",
    substitutionGroup: "fatty_protein",
    allergens: ["eggs"],
    budgetTier: "budget_friendly",
  },

  // 4. Fish & Seafood
  {
    id: "food-14",
    name: "Atlantic Salmon Fillet",
    category: "Fish",
    servingSize: 100,
    servingUnit: "g",
    calories: 208,
    protein: 20.4,
    carbs: 0.0,
    fat: 13.4,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "fatty_protein",
    allergens: ["fish"],
    budgetTier: "premium",
  },
  {
    id: "food-15",
    name: "White Fish Fillet (Tilapia/Cod)",
    category: "Fish",
    servingSize: 100,
    servingUnit: "g",
    calories: 96,
    protein: 20.1,
    carbs: 0.0,
    fat: 1.7,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "lean_protein",
    allergens: ["fish"],
    budgetTier: "moderate",
  },
  {
    id: "food-16",
    name: "Canned Tuna in Springwater (Drained)",
    category: "Fish",
    servingSize: 100,
    servingUnit: "g",
    calories: 116,
    protein: 25.5,
    carbs: 0.0,
    fat: 0.8,
    fiber: 0.0,
    dietaryType: "non_vegetarian",
    substitutionGroup: "lean_protein",
    allergens: ["fish"],
    budgetTier: "moderate",
  },

  // 5. Dairy & Curd
  {
    id: "food-17",
    name: "Fresh Paneer (Cottage Cheese)",
    category: "Common Indian Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 265,
    protein: 18.3,
    carbs: 3.2,
    fat: 20.8,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "dairy_protein",
    allergens: ["dairy"],
    budgetTier: "moderate",
  },
  {
    id: "food-18",
    name: "Low-Fat Paneer",
    category: "Common Indian Foods",
    servingSize: 100,
    servingUnit: "g",
    calories: 180,
    protein: 24.0,
    carbs: 4.0,
    fat: 7.0,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "lean_protein",
    allergens: ["dairy"],
    budgetTier: "moderate",
  },
  {
    id: "food-19",
    name: "Plain Greek Yogurt (Low Fat)",
    category: "Curd",
    servingSize: 100,
    servingUnit: "g",
    calories: 59,
    protein: 10.0,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "dairy_protein",
    allergens: ["dairy"],
    budgetTier: "moderate",
  },
  {
    id: "food-20",
    name: "Traditional Indian Curd (Dahi)",
    category: "Curd",
    servingSize: 100,
    servingUnit: "g",
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "dairy_protein",
    allergens: ["dairy"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-21",
    name: "Skimmed Milk",
    category: "Milk",
    servingSize: 250,
    servingUnit: "ml (1 cup)",
    calories: 88,
    protein: 8.5,
    carbs: 12.5,
    fat: 0.5,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "dairy_protein",
    allergens: ["dairy"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-22",
    name: "Whey Protein Isolate",
    category: "Milk",
    servingSize: 30,
    servingUnit: "g (1 scoop)",
    calories: 120,
    protein: 25.0,
    carbs: 1.5,
    fat: 1.0,
    fiber: 0.0,
    dietaryType: "vegetarian",
    substitutionGroup: "lean_protein",
    allergens: ["dairy"],
    budgetTier: "premium",
  },

  // 6. Legumes & Plant Proteins
  {
    id: "food-23",
    name: "Soya Chunks (Raw)",
    category: "Common Indian Foods",
    servingSize: 50,
    servingUnit: "g",
    calories: 172,
    protein: 26.0,
    carbs: 16.5,
    fat: 0.5,
    fiber: 6.5,
    dietaryType: "vegan",
    substitutionGroup: "lean_protein",
    allergens: ["soy"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-24",
    name: "Firm Tofu",
    category: "Legumes",
    servingSize: 100,
    servingUnit: "g",
    calories: 83,
    protein: 10.0,
    carbs: 1.9,
    fat: 5.3,
    fiber: 0.9,
    dietaryType: "vegan",
    substitutionGroup: "lean_protein",
    allergens: ["soy"],
    budgetTier: "moderate",
  },
  {
    id: "food-25",
    name: "Cooked Yellow Moong Dal",
    category: "Legumes",
    servingSize: 150,
    servingUnit: "g (1 medium bowl)",
    calories: 147,
    protein: 9.8,
    carbs: 24.5,
    fat: 0.8,
    fiber: 5.6,
    dietaryType: "vegan",
    substitutionGroup: "plant_protein",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-26",
    name: "Cooked Chana Masala (Chickpeas)",
    category: "Common Indian Foods",
    servingSize: 150,
    servingUnit: "g (1 medium bowl)",
    calories: 198,
    protein: 10.2,
    carbs: 32.4,
    fat: 3.1,
    fiber: 7.4,
    dietaryType: "vegan",
    substitutionGroup: "plant_protein",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-27",
    name: "Cooked Rajma (Red Kidney Beans)",
    category: "Common Indian Foods",
    servingSize: 150,
    servingUnit: "g (1 medium bowl)",
    calories: 180,
    protein: 11.5,
    carbs: 30.5,
    fat: 1.0,
    fiber: 8.2,
    dietaryType: "vegan",
    substitutionGroup: "plant_protein",
    budgetTier: "budget_friendly",
  },

  // 7. Fruits
  {
    id: "food-28",
    name: "Ripe Banana",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "medium (118g)",
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    dietaryType: "vegan",
    substitutionGroup: "simple_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-29",
    name: "Fresh Red Apple",
    category: "Fruits",
    servingSize: 1,
    servingUnit: "medium (150g)",
    calories: 78,
    protein: 0.4,
    carbs: 20.8,
    fat: 0.3,
    fiber: 3.6,
    dietaryType: "vegan",
    substitutionGroup: "simple_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-30",
    name: "Fresh Blueberries",
    category: "Fruits",
    servingSize: 100,
    servingUnit: "g",
    calories: 57,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    dietaryType: "vegan",
    substitutionGroup: "simple_carb",
    budgetTier: "premium",
  },
  {
    id: "food-31",
    name: "Fresh Papaya Cubes",
    category: "Fruits",
    servingSize: 150,
    servingUnit: "g (1 cup)",
    calories: 62,
    protein: 0.7,
    carbs: 15.0,
    fat: 0.4,
    fiber: 2.7,
    dietaryType: "vegan",
    substitutionGroup: "simple_carb",
    budgetTier: "budget_friendly",
  },

  // 8. Vegetables
  {
    id: "food-32",
    name: "Baby Spinach (Raw)",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    dietaryType: "vegan",
    substitutionGroup: "vegetable",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-33",
    name: "Steamed Broccoli Florets",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 35,
    protein: 2.4,
    carbs: 7.2,
    fat: 0.4,
    fiber: 2.6,
    dietaryType: "vegan",
    substitutionGroup: "vegetable",
    budgetTier: "moderate",
  },
  {
    id: "food-34",
    name: "Boiled Sweet Potato",
    category: "Vegetables",
    servingSize: 100,
    servingUnit: "g",
    calories: 86,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    dietaryType: "vegan",
    substitutionGroup: "complex_carb",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-35",
    name: "Cucumber & Tomato Garden Salad",
    category: "Vegetables",
    servingSize: 150,
    servingUnit: "g",
    calories: 28,
    protein: 1.2,
    carbs: 5.4,
    fat: 0.3,
    fiber: 1.8,
    dietaryType: "vegan",
    substitutionGroup: "vegetable",
    budgetTier: "budget_friendly",
  },

  // 9. Nuts, Seeds & Healthy Fats
  {
    id: "food-36",
    name: "Raw Almonds",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g (approx 23 nuts)",
    calories: 164,
    protein: 6.0,
    carbs: 6.1,
    fat: 14.2,
    fiber: 3.5,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    allergens: ["tree_nuts"],
    budgetTier: "moderate",
  },
  {
    id: "food-37",
    name: "Raw Walnuts",
    category: "Nuts",
    servingSize: 28,
    servingUnit: "g (approx 14 halves)",
    calories: 185,
    protein: 4.3,
    carbs: 3.9,
    fat: 18.5,
    fiber: 1.9,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    allergens: ["tree_nuts"],
    budgetTier: "moderate",
  },
  {
    id: "food-38",
    name: "Chia Seeds",
    category: "Seeds",
    servingSize: 15,
    servingUnit: "g (1 tbsp)",
    calories: 73,
    protein: 2.5,
    carbs: 6.3,
    fat: 4.6,
    fiber: 5.1,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    budgetTier: "moderate",
  },
  {
    id: "food-39",
    name: "Ground Flaxseeds",
    category: "Seeds",
    servingSize: 15,
    servingUnit: "g (1 tbsp)",
    calories: 80,
    protein: 2.8,
    carbs: 4.3,
    fat: 6.3,
    fiber: 4.1,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    budgetTier: "budget_friendly",
  },
  {
    id: "food-40",
    name: "Natural Peanut Butter (No Sugar)",
    category: "Nuts",
    servingSize: 32,
    servingUnit: "g (2 tbsp)",
    calories: 188,
    protein: 8.0,
    carbs: 7.0,
    fat: 16.0,
    fiber: 2.0,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    allergens: ["peanuts"],
    budgetTier: "budget_friendly",
  },
  {
    id: "food-41",
    name: "Extra Virgin Olive Oil",
    category: "Common Indian Foods",
    servingSize: 10,
    servingUnit: "ml (1 tbsp)",
    calories: 88,
    protein: 0.0,
    carbs: 0.0,
    fat: 10.0,
    fiber: 0.0,
    dietaryType: "vegan",
    substitutionGroup: "healthy_fat",
    budgetTier: "moderate",
  },
];

export const FOOD_CATEGORIES: FoodCategory[] = [
  "Rice",
  "Eggs",
  "Chicken",
  "Fish",
  "Milk",
  "Curd",
  "Oats",
  "Fruits",
  "Vegetables",
  "Nuts",
  "Seeds",
  "Legumes",
  "Grains",
  "Common Indian Foods",
];

export function searchFoods(
  query: string,
  categoryFilter?: FoodCategory | "All",
  dietaryFilter?: DietaryType | "All"
): FoodItem[] {
  const cleanQuery = query.toLowerCase().trim();

  return FOOD_DATABASE.filter((food) => {
    const matchesQuery =
      !cleanQuery ||
      food.name.toLowerCase().includes(cleanQuery) ||
      food.category.toLowerCase().includes(cleanQuery) ||
      food.substitutionGroup.toLowerCase().includes(cleanQuery);

    const matchesCategory =
      !categoryFilter || categoryFilter === "All" || food.category === categoryFilter;

    let matchesDiet = true;
    if (dietaryFilter && dietaryFilter !== "All") {
      if (dietaryFilter === "vegetarian") {
        matchesDiet = food.dietaryType === "vegetarian" || food.dietaryType === "vegan";
      } else if (dietaryFilter === "vegan") {
        matchesDiet = food.dietaryType === "vegan";
      } else if (dietaryFilter === "eggetarian") {
        matchesDiet =
          food.dietaryType === "vegetarian" ||
          food.dietaryType === "vegan" ||
          food.dietaryType === "eggetarian";
      }
    }

    return matchesQuery && matchesCategory && matchesDiet;
  });
}

export function getFoodById(id: string): FoodItem | undefined {
  return FOOD_DATABASE.find((item) => item.id === id);
}
