import { ExerciseItem, MuscleGroup, EquipmentType, ExerciseDifficulty } from "@/types/workout";

export const EXERCISE_DATABASE: ExerciseItem[] = [
  // ==========================================
  // CHEST
  // ==========================================
  {
    id: "ex-chest-1",
    name: "Barbell Flat Bench Press",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Lie back on bench with eyes under barbell. Grip bar slightly wider than shoulder-width. Retract scapulae, unrack, lower bar with controlled eccentric to mid-chest. Drive feet into the ground and press up explosively.",
    defaultSets: 4,
    defaultReps: "6-8",
    restTimeSeconds: 120,
    isBodyweight: false,
  },
  {
    id: "ex-chest-2",
    name: "Incline Dumbbell Bench Press",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Set adjustable bench to 30-45 degrees. Kick dumbbells up to starting position. Lower slowly until dumbbells align with upper pecs, then drive upward without clanking weights together at top.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-chest-3",
    name: "Chest Dips (Forward Lean)",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Mount parallel dip bars. Lean torso forward at roughly 30 degrees and tuck chin. Lower until shoulders are below elbows for full pectoral stretch. Press back up through pecs to 95% lockout.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 90,
    isBodyweight: true,
  },
  {
    id: "ex-chest-4",
    name: "Standing Cable Crossover",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Set pulleys at shoulder or high level. Take a staggered stance. With a slight bend in elbows, bring hands forward in a hugging arc until knuckles meet or cross slightly. Squeeze chest for 1 second.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-chest-5",
    name: "Classic Push-ups",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Assume high plank position with hands slightly outside shoulders. Engage glutes and core so body forms straight plank. Lower chest to 1 inch above floor, pause, and press up smoothly.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 60,
    isBodyweight: true,
  },
  {
    id: "ex-chest-6",
    name: "Resistance Band Chest Press",
    category: "chest",
    muscleGroup: "Chest",
    secondaryMuscles: ["Triceps", "Shoulders"],
    equipment: "bands",
    difficulty: "beginner",
    instructions: "Loop resistance band behind upper back or anchor to post. Grip handles and press forward extending arms against the elastic resistance. Ideal for home and warm-up training.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 45,
    isBodyweight: false,
  },

  // ==========================================
  // BACK
  // ==========================================
  {
    id: "ex-back-1",
    name: "Conventional Barbell Deadlift",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Hamstrings", "Glutes", "Forearms"],
    equipment: "barbell",
    difficulty: "advanced",
    instructions: "Stand with feet hip-width under bar (bar over midfoot). Hinge at hips to grip bar just outside shins. Pull chest tall, engage lats, take deep diaphragmatic breath, and push the floor away.",
    defaultSets: 4,
    defaultReps: "5",
    restTimeSeconds: 180,
    isBodyweight: false,
  },
  {
    id: "ex-back-2",
    name: "Pull-ups (Overhand Grip)",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms", "Shoulders"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Grip pull-up bar wider than shoulder-width with overhand grip. Depress shoulder blades down, pull chest toward bar driving elbows toward hip pockets. Control lower to dead hang.",
    defaultSets: 4,
    defaultReps: "6-10",
    restTimeSeconds: 120,
    isBodyweight: true,
  },
  {
    id: "ex-back-3",
    name: "Barbell Bent-Over Row",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms", "Abs"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Hinge at hips to a 45-degree torso angle with flat back. Pull bar towards lower abdomen, pinching scapulae together at peak contraction. Lower under control without bobbing torso.",
    defaultSets: 4,
    defaultReps: "8-10",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-back-4",
    name: "Seated Cable Row (Neutral Grip)",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Sit upright with feet on footrests and knees slightly unlocked. Pull V-bar handle towards belly button keeping chest up and elbows tucked. Squeeze mid-back for 1 second before releasing.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-back-5",
    name: "Single-Arm Dumbbell Row",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Support knee and hand on flat bench. With free hand holding dumbbell, pull weight upward along an arc towards hip pocket, avoiding torso rotation.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-back-6",
    name: "Lat Pulldown (Wide Grip)",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Anchor thighs under pads. Grasp wide bar with overhand grip. Lean back roughly 10 degrees and pull bar smoothly to upper chest, emphasizing lat engagement over arm pulling.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-back-7",
    name: "Inverted Bodyweight Row",
    category: "back",
    muscleGroup: "Back",
    secondaryMuscles: ["Biceps", "Abs"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Position bar at waist height in rack or use sturdy table. Hang under bar with heels on floor and body rigid. Pull chest to touch bar, pause, and lower smoothly.",
    defaultSets: 3,
    defaultReps: "10-15",
    restTimeSeconds: 60,
    isBodyweight: true,
  },

  // ==========================================
  // SHOULDERS
  // ==========================================
  {
    id: "ex-shld-1",
    name: "Overhead Barbell Press (Military Press)",
    category: "shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Abs"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Stand with feet shoulder-width, bar resting on front delts. Brace core and glutes. Press bar straight up, pulling head slightly back as bar passes face, then push head forward under bar at lockout.",
    defaultSets: 4,
    defaultReps: "6-8",
    restTimeSeconds: 120,
    isBodyweight: false,
  },
  {
    id: "ex-shld-2",
    name: "Standing Dumbbell Lateral Raise",
    category: "shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Hold dumbbells at sides with slight forward torso tilt. Raise arms laterally leading with elbows until parallel to floor. Avoid using momentum or swinging hips.",
    defaultSets: 4,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-shld-3",
    name: "Seated Dumbbell Shoulder Press",
    category: "shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Sit upright with back supported. Hold dumbbells at ear height with palms facing forward or slightly semi-neutral. Press upward in smooth arc until arms are extended overhead.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-shld-4",
    name: "Cable Face Pulls",
    category: "shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Back", "Forearms"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Attach rope to upper pulley. Grip ends with thumbs backward. Step back, pull rope directly towards bridge of nose while externally rotating shoulders and separating hands.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-shld-5",
    name: "Pike Push-ups",
    category: "shoulders",
    muscleGroup: "Shoulders",
    secondaryMuscles: ["Triceps", "Abs"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Start in pushup position and walk feet forward, lifting hips high into an inverted V shape. Lower top of head towards floor between hands, then press back up.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 75,
    isBodyweight: true,
  },

  // ==========================================
  // BICEPS
  // ==========================================
  {
    id: "ex-bic-1",
    name: "Barbell Bicep Curl",
    category: "arms",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Stand tall holding barbell with shoulder-width underhand grip. Pin elbows to ribs. Curl bar upwards contracting biceps, pausing at the apex before a 2-second eccentric lower.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-bic-2",
    name: "Incline Dumbbell Curl",
    category: "arms",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Sit on incline bench (45-60 degrees). Let arms hang straight down behind torso to place maximum stretch on bicep long head. Supinate wrists as you curl upward.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-bic-3",
    name: "Hammer Curl (Neutral Grip)",
    category: "arms",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Hold dumbbells with neutral thumbs-up grip. Curl dumbbells towards shoulders without rotating wrists. Great for targeting brachialis and brachioradialis for forearm thickness.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-bic-4",
    name: "Cable Rope Bicep Curl",
    category: "arms",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Forearms"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Attach rope to low pulley. Stand close and curl hands upward, pulling rope ends apart at peak contraction for continuous muscular tension throughout whole arc.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-bic-5",
    name: "Chin-ups (Underhand Grip)",
    category: "arms",
    muscleGroup: "Biceps",
    secondaryMuscles: ["Back", "Forearms"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Grip pull-up bar with underhand grip shoulder-width apart. Pull body upward until chin completely clears the bar, focusing on intense bicep contraction.",
    defaultSets: 3,
    defaultReps: "6-10",
    restTimeSeconds: 90,
    isBodyweight: true,
  },

  // ==========================================
  // TRICEPS
  // ==========================================
  {
    id: "ex-tri-1",
    name: "Close-Grip Barbell Bench Press",
    category: "arms",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Lie on bench and grip bar shoulder-width apart (hands ~12 inches apart). Keep elbows tightly tucked against ribcage during descent to maximize tricep loading.",
    defaultSets: 3,
    defaultReps: "8-10",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-tri-2",
    name: "Overhead Cable Rope Tricep Extension",
    category: "arms",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Attach rope to high or mid cable. Turn body away, lean forward with staggered feet. Extend elbows overhead, spreading rope apart at full lockout to emphasize long head.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-tri-3",
    name: "Tricep Dips (Bench / Parallel Bars)",
    category: "arms",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Support body upright on dip bars or edge of flat bench. Lower body keeping torso vertical and elbows pointing straight back until 90-degree flexion, then lock out triceps.",
    defaultSets: 3,
    defaultReps: "10-15",
    restTimeSeconds: 60,
    isBodyweight: true,
  },
  {
    id: "ex-tri-4",
    name: "Skull Crushers (EZ Bar Lying Extension)",
    category: "arms",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Forearms"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Lie on flat bench holding EZ-curl bar over chest. Keeping upper arms stationary at a slight backward slant, hinge at elbows to lower bar towards crown of head. Extend back up smoothly.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-tri-5",
    name: "Diamond Push-ups",
    category: "arms",
    muscleGroup: "Triceps",
    secondaryMuscles: ["Chest"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "In pushup position, place hands close together with thumbs and index fingers forming diamond shape. Lower chest to touch hands and push up through triceps.",
    defaultSets: 3,
    defaultReps: "10-15",
    restTimeSeconds: 60,
    isBodyweight: true,
  },

  // ==========================================
  // QUADS
  // ==========================================
  {
    id: "ex-quad-1",
    name: "Barbell High-Bar Back Squat",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings", "Abs"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Place barbell firmly across upper trapezius. Set feet shoulder-width with toes flared 15-30 degrees. Break at knees and hips simultaneously, descend below parallel with upright torso, and drive up through midfoot.",
    defaultSets: 4,
    defaultReps: "6-8",
    restTimeSeconds: 150,
    isBodyweight: false,
  },
  {
    id: "ex-quad-2",
    name: "Leg Press 45°",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Position feet shoulder-width on center sled. Unlock safety pins. Lower sled under strict control until knees reach 90-degree angle. Press platform away without hyperextending knees.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-quad-3",
    name: "Bulgarian Split Squat",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Place top of one foot behind you on flat bench. Lower front knee until thigh is parallel with floor while maintaining upright torso. Drive through front heel to return to top.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-quad-4",
    name: "Leg Extension Machine",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Align knee joint with machine pivot axis. Pad should sit across lower shins. Extend legs upwards to full contraction, holding peak squeeze for 1 full second before lowering slowly.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-quad-5",
    name: "Bodyweight Air Squats",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Stand with feet shoulder-width. Extend arms forward for balance. Sit hips back and down below parallel keeping chest elevated and knees tracking over toes. Stand up quickly.",
    defaultSets: 3,
    defaultReps: "20-25",
    restTimeSeconds: 45,
    isBodyweight: true,
  },
  {
    id: "ex-quad-6",
    name: "Goblet Squat (Dumbbell or Kettlebell)",
    category: "legs",
    muscleGroup: "Quads",
    secondaryMuscles: ["Glutes", "Abs"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Hold single heavy dumbbell or kettlebell vertically against sternum. Squat deep between knees while keeping elbows tucked inside thighs. Stand tall squeezing glutes.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },

  // ==========================================
  // HAMSTRINGS
  // ==========================================
  {
    id: "ex-ham-1",
    name: "Romanian Deadlift (RDL)",
    category: "legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes", "Back"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Stand tall holding barbell at thighs. Unlock knees slightly (soft bend) and keep them fixed. Push hips straight back towards wall behind you until hamstrings are deeply stretched. Snap hips forward to return.",
    defaultSets: 4,
    defaultReps: "8-10",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-ham-2",
    name: "Lying Leg Curl Machine",
    category: "legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Calves"],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Lie face down with roller pad positioned just below calf muscles. Curl heels towards glutes without letting hips lift off bench. Control 3-second negative eccentric return.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-ham-3",
    name: "Dumbbell Romanian Deadlift",
    category: "legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Hold pair of dumbbells in front of thighs. Hinge back at hips sliding weights closely down shins. Feel deep tension in posterior chain, then drive hips through.",
    defaultSets: 3,
    defaultReps: "10-12",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-ham-4",
    name: "Nordic Hamstring Curl",
    category: "legs",
    muscleGroup: "Hamstrings",
    secondaryMuscles: ["Glutes"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Kneel with ankles firmly anchored under pad or partner. Keeping hips straight, slowly lower torso towards floor fighting gravity entirely with hamstring eccentric strength. Catch hands and push back up.",
    defaultSets: 3,
    defaultReps: "5-8",
    restTimeSeconds: 120,
    isBodyweight: true,
  },

  // ==========================================
  // GLUTES
  // ==========================================
  {
    id: "ex-glu-1",
    name: "Barbell Hip Thrust",
    category: "legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings", "Quads"],
    equipment: "barbell",
    difficulty: "intermediate",
    instructions: "Rest upper back against bench with barbell across hip crease (cushioned with pad). Drive through heels until hips reach full extension parallel to floor. Lock out and squeeze glutes hard for 2 seconds.",
    defaultSets: 4,
    defaultReps: "8-12",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-glu-2",
    name: "Dumbbell Walking Lunges",
    category: "legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Quads", "Hamstrings"],
    equipment: "dumbbell",
    difficulty: "beginner",
    instructions: "Hold dumbbells at sides. Take deep step forward, dropping back knee gently to hover 1 inch above floor. Drive upward through front heel to step smoothly into next stride.",
    defaultSets: 3,
    defaultReps: "12 steps/leg",
    restTimeSeconds: 75,
    isBodyweight: false,
  },
  {
    id: "ex-glu-3",
    name: "Cable Glute Kickbacks",
    category: "legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Attach ankle cuff to low pulley cable. Stand facing machine with slight forward hip hinge. Kick leg straight back and slightly outward, focusing on peak upper glute contraction.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-glu-4",
    name: "Bodyweight Glute Bridges",
    category: "legs",
    muscleGroup: "Glutes",
    secondaryMuscles: ["Hamstrings"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Lie on back with knees bent and feet flat on floor hip-width apart. Drive hips upward toward ceiling by contracting glutes. Hold top position for 2 seconds before descending.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 45,
    isBodyweight: true,
  },

  // ==========================================
  // CALVES
  // ==========================================
  {
    id: "ex-calf-1",
    name: "Standing Barbell Calf Raise",
    category: "legs",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Stand with balls of feet on elevated block. Allow heels to drop deeply for full stretch. Explode upward onto toes, holding peak contraction for 2 seconds at the very top.",
    defaultSets: 4,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-calf-2",
    name: "Seated Machine Calf Raise",
    category: "legs",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "machine",
    difficulty: "beginner",
    instructions: "Sit with knees bent at 90 degrees under pads. Lower heels into deep Achilles stretch, then press balls of feet into pad to target the soleus muscle.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-calf-3",
    name: "Single-Leg Bodyweight Calf Raise",
    category: "legs",
    muscleGroup: "Calves",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Stand on stair edge on one foot, lightly holding railing for balance. Lower heel below step, then rise onto tiptoes smoothly. Perform high repetition set.",
    defaultSets: 3,
    defaultReps: "15-20/leg",
    restTimeSeconds: 45,
    isBodyweight: true,
  },

  // ==========================================
  // ABS & CORE
  // ==========================================
  {
    id: "ex-abs-1",
    name: "Hanging Leg Raise",
    category: "core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Forearms"],
    equipment: "bodyweight",
    difficulty: "intermediate",
    instructions: "Hang from pullup bar with straight arms. Without swinging or using momentum, contract abs to curl pelvis upward, bringing feet or knees up to horizontal or bar height.",
    defaultSets: 3,
    defaultReps: "10-15",
    restTimeSeconds: 60,
    isBodyweight: true,
  },
  {
    id: "ex-abs-2",
    name: "Cable Woodchopper (High to Low)",
    category: "core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Shoulders"],
    equipment: "cable",
    difficulty: "beginner",
    instructions: "Set pulley high. Stand sideways, grip handle with both arms extended. Rotate torso diagonally downward across opposite knee using abdominal oblique drive.",
    defaultSets: 3,
    defaultReps: "12/side",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-abs-3",
    name: "Ab Wheel Rollout",
    category: "core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Back", "Shoulders"],
    equipment: "bodyweight",
    difficulty: "advanced",
    instructions: "Kneel with hands on ab wheel. Brace core and roll wheel forward extending torso as low as comfortable without sagging lower back. Contract lats and abs to pull back.",
    defaultSets: 3,
    defaultReps: "8-12",
    restTimeSeconds: 75,
    isBodyweight: true,
  },
  {
    id: "ex-abs-4",
    name: "Forearm Plank with Hip Dips",
    category: "core",
    muscleGroup: "Abs",
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Rest on forearms and toes in solid plank. Slowly rotate hips to tap floor on left side, return to center, then rotate to tap right side. Keep core braced firmly.",
    defaultSets: 3,
    defaultReps: "16-20 total",
    restTimeSeconds: 45,
    isBodyweight: true,
  },
  {
    id: "ex-abs-5",
    name: "Bicycle Crunches",
    category: "core",
    muscleGroup: "Abs",
    secondaryMuscles: [],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Lie on back with hands behind head and legs elevated. Alternate bringing opposite elbow towards opposite knee while extending other leg straight out.",
    defaultSets: 3,
    defaultReps: "20 total",
    restTimeSeconds: 45,
    isBodyweight: true,
  },

  // ==========================================
  // FOREARMS
  // ==========================================
  {
    id: "ex-fore-1",
    name: "Barbell Wrist Curl",
    category: "arms",
    muscleGroup: "Forearms",
    secondaryMuscles: [],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Kneel beside bench, resting forearms across bench with wrists hanging over edge (palms up). Curl wrists upward, squeezing forearm flexors tightly.",
    defaultSets: 3,
    defaultReps: "15-20",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-fore-2",
    name: "Heavy Dumbbell Farmer's Walk",
    category: "arms",
    muscleGroup: "Forearms",
    secondaryMuscles: ["Back", "Shoulders", "Abs"],
    equipment: "dumbbell",
    difficulty: "intermediate",
    instructions: "Pick up two heavy dumbbells with strong grip. Stand with proud chest and braced core. Walk forward with short, measured steps for 30-45 seconds without leaning.",
    defaultSets: 3,
    defaultReps: "40 meters",
    restTimeSeconds: 90,
    isBodyweight: false,
  },
  {
    id: "ex-fore-3",
    name: "Reverse EZ-Bar Bicep Curl",
    category: "arms",
    muscleGroup: "Forearms",
    secondaryMuscles: ["Biceps"],
    equipment: "barbell",
    difficulty: "beginner",
    instructions: "Hold EZ curl bar with overhand (pronated) grip. Curl bar upward while keeping wrists completely rigid, placing intense tension on brachioradialis.",
    defaultSets: 3,
    defaultReps: "12-15",
    restTimeSeconds: 60,
    isBodyweight: false,
  },
  {
    id: "ex-fore-4",
    name: "Dead Hang from Pull-up Bar",
    category: "arms",
    muscleGroup: "Forearms",
    secondaryMuscles: ["Back", "Shoulders"],
    equipment: "bodyweight",
    difficulty: "beginner",
    instructions: "Grip pull-up bar with overhand grip and hang with feet off floor. Keep shoulders active (not completely resting on joints). Hold for max time to build crushing grip.",
    defaultSets: 3,
    defaultReps: "45-60 sec",
    restTimeSeconds: 60,
    isBodyweight: true,
  },
];

// Helper functions
export function getAllExercises(): ExerciseItem[] {
  return EXERCISE_DATABASE;
}

export function getExerciseById(id: string): ExerciseItem | undefined {
  return EXERCISE_DATABASE.find((ex) => ex.id === id);
}

export function searchExercises(
  query: string,
  muscleFilter?: MuscleGroup | "All",
  equipmentFilter?: EquipmentType | "All",
  difficultyFilter?: ExerciseDifficulty | "All"
): ExerciseItem[] {
  const q = query.toLowerCase().trim();

  return EXERCISE_DATABASE.filter((ex) => {
    // Text search
    if (q) {
      const matchName = ex.name.toLowerCase().includes(q);
      const matchMuscle = ex.muscleGroup.toLowerCase().includes(q);
      const matchSecondary = ex.secondaryMuscles.some((m) => m.toLowerCase().includes(q));
      const matchCategory = ex.category.toLowerCase().includes(q);
      if (!matchName && !matchMuscle && !matchSecondary && !matchCategory) {
        return false;
      }
    }

    // Muscle filter
    if (muscleFilter && muscleFilter !== "All") {
      if (ex.muscleGroup !== muscleFilter && !ex.secondaryMuscles.includes(muscleFilter)) {
        return false;
      }
    }

    // Equipment filter
    if (equipmentFilter && equipmentFilter !== "All") {
      if (ex.equipment !== equipmentFilter) {
        return false;
      }
    }

    // Difficulty filter
    if (difficultyFilter && difficultyFilter !== "All") {
      if (ex.difficulty !== difficultyFilter) {
        return false;
      }
    }

    return true;
  });
}
