import { WorkoutSplitPlan, WorkoutRoutine, WarmupCooldownProtocol } from "@/types/workout";

export const WORKOUT_SPLITS: WorkoutSplitPlan[] = [
  // 1. FULL BODY (3-Day Plan)
  {
    id: "split-full-body",
    name: "Full Body Mastery (3 Days/Week)",
    splitType: "full_body",
    daysPerWeek: 3,
    recommendedExperience: "beginner",
    description: "High-frequency training hitting every major muscle group 3 times per week. Ideal for beginners, general fitness, fat loss, and time-restricted lifters.",
    educationalOverview: {
      targetAudience: "Beginners, busy professionals, and athletes needing maximal muscle protein synthesis frequency with 4 complete rest/recovery days.",
      weeklySchedule: ["Monday: Workout A", "Tuesday: Rest", "Wednesday: Workout B", "Thursday: Rest", "Friday: Workout A", "Saturday & Sunday: Active Recovery"],
      pros: ["High frequency (3x/week per muscle group)", "Maximum scheduling flexibility", "Excellent caloric expenditure for fat loss", "Low daily fatigue per muscle group"],
      cons: ["Longer individual workout sessions", "Cannot perform extreme volume per body part in a single day"],
      recoveryAdvice: "Ensure 48 hours of recovery between sessions. Prioritize sleep and hydration on rest days.",
    },
    routines: [
      {
        id: "fb-routine-a",
        dayLabel: "Day 1 • Monday / Friday",
        name: "Full Body A: Squat & Horizontal Push/Pull",
        splitType: "full_body",
        targetMuscles: ["Quads", "Chest", "Back", "Shoulders", "Abs"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-quad-1", name: "Barbell High-Bar Back Squat", muscleGroup: "Quads", equipment: "barbell", sets: 3, reps: "6-8", restTimeSeconds: 150 },
          { exerciseId: "ex-chest-1", name: "Barbell Flat Bench Press", muscleGroup: "Chest", equipment: "barbell", sets: 3, reps: "8-10", restTimeSeconds: 120 },
          { exerciseId: "ex-back-3", name: "Barbell Bent-Over Row", muscleGroup: "Back", equipment: "barbell", sets: 3, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-shld-2", name: "Standing Dumbbell Lateral Raise", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 3, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-abs-1", name: "Hanging Leg Raise", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
      {
        id: "fb-routine-b",
        dayLabel: "Day 2 • Wednesday",
        name: "Full Body B: Hinge, Vertical Push/Pull & Arms",
        splitType: "full_body",
        targetMuscles: ["Hamstrings", "Back", "Shoulders", "Biceps", "Triceps"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-ham-1", name: "Romanian Deadlift (RDL)", muscleGroup: "Hamstrings", equipment: "barbell", sets: 3, reps: "8-10", restTimeSeconds: 120 },
          { exerciseId: "ex-back-2", name: "Pull-ups (Overhand Grip)", muscleGroup: "Back", equipment: "bodyweight", sets: 3, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-shld-1", name: "Overhead Barbell Press", muscleGroup: "Shoulders", equipment: "barbell", sets: 3, reps: "8-10", restTimeSeconds: 120 },
          { exerciseId: "ex-bic-1", name: "Barbell Bicep Curl", muscleGroup: "Biceps", equipment: "barbell", sets: 3, reps: "10-12", restTimeSeconds: 60 },
          { exerciseId: "ex-tri-2", name: "Overhead Cable Rope Tricep Extension", muscleGroup: "Triceps", equipment: "cable", sets: 3, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
    ],
  },

  // 2. UPPER / LOWER (4-Day Plan)
  {
    id: "split-upper-lower",
    name: "Upper / Lower Split (4 Days/Week)",
    splitType: "upper_lower",
    daysPerWeek: 4,
    recommendedExperience: "intermediate",
    description: "The gold-standard balance of frequency, volume, and recovery. Trains upper body and lower body twice each week.",
    educationalOverview: {
      targetAudience: "Intermediate lifters, hypertrophy athletes, and strength trainees seeking optimal muscle growth without systemic overtraining.",
      weeklySchedule: ["Monday: Upper Power", "Tuesday: Lower Power", "Wednesday: Rest", "Thursday: Upper Hypertrophy", "Friday: Lower Hypertrophy", "Weekend: Rest"],
      pros: ["Optimal 2x/week per muscle frequency", "Clean separation of upper and lower fatigue", "Ample rest days for joint and CNS recovery"],
      cons: ["Upper sessions can be lengthy due to multiple muscle groups", "Requires consistency across 4 set workout days"],
      recoveryAdvice: "Ensure Wednesday remains a dedicated rest or light cardio day to split the two training blocks.",
    },
    routines: [
      {
        id: "ul-upper-1",
        dayLabel: "Day 1 • Monday",
        name: "Upper Body Power: Heavy Presses & Rows",
        splitType: "upper_lower",
        targetMuscles: ["Chest", "Back", "Shoulders", "Biceps", "Triceps"],
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "ex-chest-1", name: "Barbell Flat Bench Press", muscleGroup: "Chest", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-back-3", name: "Barbell Bent-Over Row", muscleGroup: "Back", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-shld-1", name: "Overhead Barbell Press", muscleGroup: "Shoulders", equipment: "barbell", sets: 3, reps: "6-8", restTimeSeconds: 90 },
          { exerciseId: "ex-back-2", name: "Pull-ups (Overhand Grip)", muscleGroup: "Back", equipment: "bodyweight", sets: 3, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-bic-2", name: "Incline Dumbbell Curl", muscleGroup: "Biceps", equipment: "dumbbell", sets: 3, reps: "10-12", restTimeSeconds: 60 },
          { exerciseId: "ex-tri-1", name: "Close-Grip Barbell Bench Press", muscleGroup: "Triceps", equipment: "barbell", sets: 3, reps: "8-10", restTimeSeconds: 75 },
        ],
      },
      {
        id: "ul-lower-1",
        dayLabel: "Day 2 • Tuesday",
        name: "Lower Body Power: Squats & Posterior Chain",
        splitType: "upper_lower",
        targetMuscles: ["Quads", "Hamstrings", "Glutes", "Calves", "Abs"],
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "ex-quad-1", name: "Barbell High-Bar Back Squat", muscleGroup: "Quads", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 150 },
          { exerciseId: "ex-ham-1", name: "Romanian Deadlift (RDL)", muscleGroup: "Hamstrings", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 120 },
          { exerciseId: "ex-quad-3", name: "Bulgarian Split Squat", muscleGroup: "Quads", equipment: "dumbbell", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-calf-1", name: "Standing Barbell Calf Raise", muscleGroup: "Calves", equipment: "barbell", sets: 4, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-abs-3", name: "Ab Wheel Rollout", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 60 },
        ],
      },
      {
        id: "ul-upper-2",
        dayLabel: "Day 3 • Thursday",
        name: "Upper Body Hypertrophy: Dumbbells & Cables",
        splitType: "upper_lower",
        targetMuscles: ["Chest", "Back", "Shoulders", "Biceps", "Triceps"],
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "ex-chest-2", name: "Incline Dumbbell Bench Press", muscleGroup: "Chest", equipment: "dumbbell", sets: 4, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-back-4", name: "Seated Cable Row (Neutral Grip)", muscleGroup: "Back", equipment: "cable", sets: 4, reps: "10-12", restTimeSeconds: 75 },
          { exerciseId: "ex-chest-4", name: "Standing Cable Crossover", muscleGroup: "Chest", equipment: "cable", sets: 3, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-shld-2", name: "Standing Dumbbell Lateral Raise", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 4, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-shld-4", name: "Cable Face Pulls", muscleGroup: "Shoulders", equipment: "cable", sets: 3, reps: "15-20", restTimeSeconds: 60 },
          { exerciseId: "ex-tri-2", name: "Overhead Cable Rope Tricep Extension", muscleGroup: "Triceps", equipment: "cable", sets: 3, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
      {
        id: "ul-lower-2",
        dayLabel: "Day 4 • Friday",
        name: "Lower Body Hypertrophy: Thrusts & Leg Machines",
        splitType: "upper_lower",
        targetMuscles: ["Glutes", "Quads", "Hamstrings", "Calves", "Abs"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-glu-1", name: "Barbell Hip Thrust", muscleGroup: "Glutes", equipment: "barbell", sets: 4, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-quad-2", name: "Leg Press 45°", muscleGroup: "Quads", equipment: "machine", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-ham-2", name: "Lying Leg Curl Machine", muscleGroup: "Hamstrings", equipment: "machine", sets: 3, reps: "10-12", restTimeSeconds: 60 },
          { exerciseId: "ex-quad-4", name: "Leg Extension Machine", muscleGroup: "Quads", equipment: "machine", sets: 3, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-calf-2", name: "Seated Machine Calf Raise", muscleGroup: "Calves", equipment: "machine", sets: 3, reps: "15-20", restTimeSeconds: 60 },
          { exerciseId: "ex-abs-1", name: "Hanging Leg Raise", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
    ],
  },

  // 3. PUSH PULL LEGS (6-Day or 3-Day Plan)
  {
    id: "split-ppl",
    name: "Push Pull Legs (PPL Hypertrophy)",
    splitType: "push_pull_legs",
    daysPerWeek: 6,
    recommendedExperience: "intermediate",
    description: "The most popular hypertrophy split worldwide. Groups biomechanically synergistic muscles together for focused pump and complete local recovery.",
    educationalOverview: {
      targetAudience: "Lifters seeking maximal muscle hypertrophy who can commit to 5-6 training sessions per week.",
      weeklySchedule: ["Mon: Push A", "Tue: Pull A", "Wed: Legs A", "Thu: Push B", "Fri: Pull B", "Sat: Legs B", "Sun: Rest"],
      pros: ["Zero muscle overlap (muscles rest 72h before repeat)", "Super high focus per workout", "Can be scaled to 3 days or 6 days"],
      cons: ["Demands 6 days commitment for full rotation", "Can cause high cumulative fatigue if sleep is sub-optimal"],
      recoveryAdvice: "Deload every 6-8 weeks by reducing sets by 40% to prevent joint wear.",
    },
    routines: [
      {
        id: "ppl-push-a",
        dayLabel: "Day 1 • Monday",
        name: "Push A: Chest Focus, Delts & Triceps",
        splitType: "push_pull_legs",
        targetMuscles: ["Chest", "Shoulders", "Triceps"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-chest-1", name: "Barbell Flat Bench Press", muscleGroup: "Chest", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-chest-2", name: "Incline Dumbbell Bench Press", muscleGroup: "Chest", equipment: "dumbbell", sets: 3, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-shld-3", name: "Seated Dumbbell Shoulder Press", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 3, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-shld-2", name: "Standing Dumbbell Lateral Raise", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 4, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-tri-2", name: "Overhead Cable Rope Tricep Extension", muscleGroup: "Triceps", equipment: "cable", sets: 3, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-chest-3", name: "Chest Dips (Forward Lean)", muscleGroup: "Chest", equipment: "bodyweight", sets: 3, reps: "To Failure", restTimeSeconds: 90 },
        ],
      },
      {
        id: "ppl-pull-a",
        dayLabel: "Day 2 • Tuesday",
        name: "Pull A: Lat Width, Upper Back & Biceps",
        splitType: "push_pull_legs",
        targetMuscles: ["Back", "Biceps", "Forearms"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-back-2", name: "Pull-ups (Overhand Grip)", muscleGroup: "Back", equipment: "bodyweight", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-back-3", name: "Barbell Bent-Over Row", muscleGroup: "Back", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-back-4", name: "Seated Cable Row (Neutral Grip)", muscleGroup: "Back", equipment: "cable", sets: 3, reps: "10-12", restTimeSeconds: 75 },
          { exerciseId: "ex-shld-4", name: "Cable Face Pulls", muscleGroup: "Shoulders", equipment: "cable", sets: 3, reps: "15-20", restTimeSeconds: 60 },
          { exerciseId: "ex-bic-1", name: "Barbell Bicep Curl", muscleGroup: "Biceps", equipment: "barbell", sets: 3, reps: "8-12", restTimeSeconds: 75 },
          { exerciseId: "ex-bic-3", name: "Hammer Curl (Neutral Grip)", muscleGroup: "Biceps", equipment: "dumbbell", sets: 3, reps: "10-12", restTimeSeconds: 60 },
        ],
      },
      {
        id: "ppl-legs-a",
        dayLabel: "Day 3 • Wednesday",
        name: "Legs A: Quad Dominance, Glutes & Calves",
        splitType: "push_pull_legs",
        targetMuscles: ["Quads", "Glutes", "Hamstrings", "Calves", "Abs"],
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "ex-quad-1", name: "Barbell High-Bar Back Squat", muscleGroup: "Quads", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 150 },
          { exerciseId: "ex-ham-1", name: "Romanian Deadlift (RDL)", muscleGroup: "Hamstrings", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 120 },
          { exerciseId: "ex-quad-2", name: "Leg Press 45°", muscleGroup: "Quads", equipment: "machine", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-ham-2", name: "Lying Leg Curl Machine", muscleGroup: "Hamstrings", equipment: "machine", sets: 3, reps: "10-12", restTimeSeconds: 60 },
          { exerciseId: "ex-calf-1", name: "Standing Barbell Calf Raise", muscleGroup: "Calves", equipment: "barbell", sets: 4, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-abs-1", name: "Hanging Leg Raise", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
    ],
  },

  // 4. BRO SPLIT (5-Day Plan)
  {
    id: "split-bro-split",
    name: "Classic Bro Split (5 Days/Week)",
    splitType: "bro_split",
    daysPerWeek: 5,
    recommendedExperience: "intermediate",
    description: "One body part per day. Allows extreme localized volume and intensity for each muscle with 7 full days of recovery per group.",
    educationalOverview: {
      targetAudience: "Bodybuilders who enjoy high volume per muscle group and legendary localized muscle pumps.",
      weeklySchedule: ["Mon: Chest", "Tue: Back", "Wed: Shoulders", "Thu: Legs", "Fri: Arms", "Weekend: Rest"],
      pros: ["High single-session volume per muscle", "Maximum pump sensation", "Simplicity and focus"],
      cons: ["Low frequency (1x per week)", "Missed workouts disrupt entire weekly sequence"],
      recoveryAdvice: "Because each muscle is hit with high volume once a week, emphasize eccentric control and stretching post-workout.",
    },
    routines: [
      {
        id: "bro-chest",
        dayLabel: "Day 1 • Monday",
        name: "Chest Demolition Day",
        splitType: "bro_split",
        targetMuscles: ["Chest"],
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "ex-chest-1", name: "Barbell Flat Bench Press", muscleGroup: "Chest", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-chest-2", name: "Incline Dumbbell Bench Press", muscleGroup: "Chest", equipment: "dumbbell", sets: 4, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-chest-3", name: "Chest Dips", muscleGroup: "Chest", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-chest-4", name: "Standing Cable Crossover", muscleGroup: "Chest", equipment: "cable", sets: 4, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
      {
        id: "bro-back",
        dayLabel: "Day 2 • Tuesday",
        name: "Back Thickness & Lat Width",
        splitType: "bro_split",
        targetMuscles: ["Back"],
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "ex-back-1", name: "Conventional Barbell Deadlift", muscleGroup: "Back", equipment: "barbell", sets: 4, reps: "5", restTimeSeconds: 180 },
          { exerciseId: "ex-back-2", name: "Weighted Pull-ups", muscleGroup: "Back", equipment: "bodyweight", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-back-3", name: "Barbell Bent-Over Row", muscleGroup: "Back", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-back-4", name: "Seated Cable Row", muscleGroup: "Back", equipment: "cable", sets: 3, reps: "10-12", restTimeSeconds: 75 },
        ],
      },
      {
        id: "bro-shoulders",
        dayLabel: "Day 3 • Wednesday",
        name: "3D Boulder Shoulders",
        splitType: "bro_split",
        targetMuscles: ["Shoulders"],
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "ex-shld-1", name: "Overhead Barbell Press", muscleGroup: "Shoulders", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 120 },
          { exerciseId: "ex-shld-2", name: "Standing Dumbbell Lateral Raise", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 5, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-shld-3", name: "Seated Dumbbell Shoulder Press", muscleGroup: "Shoulders", equipment: "dumbbell", sets: 3, reps: "8-12", restTimeSeconds: 90 },
          { exerciseId: "ex-shld-4", name: "Cable Face Pulls", muscleGroup: "Shoulders", equipment: "cable", sets: 4, reps: "15-20", restTimeSeconds: 60 },
        ],
      },
      {
        id: "bro-legs",
        dayLabel: "Day 4 • Thursday",
        name: "Total Leg Warfare",
        splitType: "bro_split",
        targetMuscles: ["Quads", "Hamstrings", "Glutes", "Calves"],
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "ex-quad-1", name: "Barbell High-Bar Back Squat", muscleGroup: "Quads", equipment: "barbell", sets: 4, reps: "6-8", restTimeSeconds: 150 },
          { exerciseId: "ex-quad-2", name: "Leg Press 45°", muscleGroup: "Quads", equipment: "machine", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-ham-1", name: "Romanian Deadlift", muscleGroup: "Hamstrings", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-glu-1", name: "Barbell Hip Thrust", muscleGroup: "Glutes", equipment: "barbell", sets: 3, reps: "10-12", restTimeSeconds: 90 },
          { exerciseId: "ex-calf-1", name: "Standing Barbell Calf Raise", muscleGroup: "Calves", equipment: "barbell", sets: 4, reps: "12-15", restTimeSeconds: 60 },
        ],
      },
      {
        id: "bro-arms",
        dayLabel: "Day 5 • Friday",
        name: "Arm Super-Pump (Biceps & Triceps)",
        splitType: "bro_split",
        targetMuscles: ["Biceps", "Triceps", "Forearms"],
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "ex-tri-1", name: "Close-Grip Barbell Bench Press", muscleGroup: "Triceps", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 90 },
          { exerciseId: "ex-bic-1", name: "Barbell Bicep Curl", muscleGroup: "Biceps", equipment: "barbell", sets: 4, reps: "8-10", restTimeSeconds: 75 },
          { exerciseId: "ex-tri-2", name: "Overhead Cable Rope Extension", muscleGroup: "Triceps", equipment: "cable", sets: 3, reps: "12-15", restTimeSeconds: 60 },
          { exerciseId: "ex-bic-3", name: "Hammer Curl", muscleGroup: "Biceps", equipment: "dumbbell", sets: 3, reps: "10-12", restTimeSeconds: 60 },
          { exerciseId: "ex-fore-1", name: "Barbell Wrist Curl", muscleGroup: "Forearms", equipment: "barbell", sets: 3, reps: "15-20", restTimeSeconds: 60 },
        ],
      },
    ],
  },
];

// Dedicated Core Workouts
export const DEDICATED_CORE_WORKOUTS: WorkoutRoutine[] = [
  {
    id: "core-hypertrophy",
    dayLabel: "Core Circuit 1",
    name: "Abdominal Hypertrophy & Oblique Blast",
    splitType: "core_workout",
    targetMuscles: ["Abs"],
    estimatedMinutes: 20,
    exercises: [
      { exerciseId: "ex-abs-1", name: "Hanging Leg Raise", muscleGroup: "Abs", equipment: "bodyweight", sets: 4, reps: "12-15", restTimeSeconds: 60 },
      { exerciseId: "ex-abs-2", name: "Cable Woodchopper (High to Low)", muscleGroup: "Abs", equipment: "cable", sets: 3, reps: "12/side", restTimeSeconds: 45 },
      { exerciseId: "ex-abs-3", name: "Ab Wheel Rollout", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 60 },
      { exerciseId: "ex-abs-4", name: "Forearm Plank with Hip Dips", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "20 reps", restTimeSeconds: 45 },
    ],
  },
  {
    id: "core-stability",
    dayLabel: "Core Circuit 2",
    name: "Anti-Rotation & Isometric Core Armor",
    splitType: "core_workout",
    targetMuscles: ["Abs"],
    estimatedMinutes: 15,
    exercises: [
      { exerciseId: "ex-abs-4", name: "Forearm Plank with Hip Dips", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "60 sec hold", restTimeSeconds: 45 },
      { exerciseId: "ex-abs-5", name: "Bicycle Crunches", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "25 reps", restTimeSeconds: 45 },
      { exerciseId: "ex-fore-2", name: "Heavy Dumbbell Farmer's Walk", muscleGroup: "Forearms", equipment: "dumbbell", sets: 3, reps: "45 sec walk", restTimeSeconds: 60 },
    ],
  },
];

// Dedicated Home Workouts (100% Bodyweight / Equipment-Free)
export const DEDICATED_HOME_WORKOUTS: WorkoutRoutine[] = [
  {
    id: "home-fullbody-burner",
    dayLabel: "Home Calisthenics",
    name: "Zero-Equipment Calisthenics Full Body",
    splitType: "home_workout",
    targetMuscles: ["Chest", "Back", "Quads", "Abs", "Glutes"],
    estimatedMinutes: 35,
    isHomeWorkout: true,
    exercises: [
      { exerciseId: "ex-chest-5", name: "Classic Push-ups", muscleGroup: "Chest", equipment: "bodyweight", sets: 4, reps: "15-20", restTimeSeconds: 60 },
      { exerciseId: "ex-quad-5", name: "Bodyweight Air Squats", muscleGroup: "Quads", equipment: "bodyweight", sets: 4, reps: "25 reps", restTimeSeconds: 45 },
      { exerciseId: "ex-back-7", name: "Inverted Bodyweight Row", muscleGroup: "Back", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 60 },
      { exerciseId: "ex-shld-5", name: "Pike Push-ups", muscleGroup: "Shoulders", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 60 },
      { exerciseId: "ex-glu-4", name: "Bodyweight Glute Bridges", muscleGroup: "Glutes", equipment: "bodyweight", sets: 3, reps: "20 reps", restTimeSeconds: 45 },
      { exerciseId: "ex-abs-5", name: "Bicycle Crunches", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "20 reps", restTimeSeconds: 45 },
    ],
  },
  {
    id: "home-upper-power",
    dayLabel: "Home Upper Body",
    name: "Bodyweight Upper Body Push/Pull Power",
    splitType: "home_workout",
    targetMuscles: ["Chest", "Shoulders", "Triceps", "Abs"],
    estimatedMinutes: 30,
    isHomeWorkout: true,
    exercises: [
      { exerciseId: "ex-chest-5", name: "Classic Push-ups", muscleGroup: "Chest", equipment: "bodyweight", sets: 4, reps: "15-20", restTimeSeconds: 60 },
      { exerciseId: "ex-tri-5", name: "Diamond Push-ups", muscleGroup: "Triceps", equipment: "bodyweight", sets: 3, reps: "12-15", restTimeSeconds: 60 },
      { exerciseId: "ex-shld-5", name: "Pike Push-ups", muscleGroup: "Shoulders", equipment: "bodyweight", sets: 3, reps: "10-12", restTimeSeconds: 60 },
      { exerciseId: "ex-tri-3", name: "Tricep Dips (Bench / Chair)", muscleGroup: "Triceps", equipment: "bodyweight", sets: 3, reps: "15 reps", restTimeSeconds: 45 },
      { exerciseId: "ex-abs-4", name: "Forearm Plank with Hip Dips", muscleGroup: "Abs", equipment: "bodyweight", sets: 3, reps: "45 sec hold", restTimeSeconds: 45 },
    ],
  },
];

// Warm-up and Cool-down Protocols
export const WARMUP_COOLDOWN_PROTOCOLS: WarmupCooldownProtocol[] = [
  {
    id: "warmup-upper",
    title: "Dynamic Upper Body Primer",
    type: "warmup",
    durationMinutes: 7,
    targetArea: "Upper Body",
    exercises: [
      { name: "Arm Circles & Cross-Body Swings", durationOrReps: "15 reps each direction", cues: "Open chest fully and mobilize rotator cuffs." },
      { name: "Band Pull-Aparts or Scapular Shrugs", durationOrReps: "20 reps", cues: "Squeeze rhomboids and retract shoulder blades without arching low back." },
      { name: "Push-up to Downward Dog", durationOrReps: "10 reps", cues: "Flow smoothly from bottom pushup into posterior chain and thoracic spine stretch." },
      { name: "Wrist Rotations & Flexor Mobility", durationOrReps: "30 seconds", cues: "Prepare wrists for heavy barbell and dumbbell pressing loads." },
    ],
  },
  {
    id: "warmup-lower",
    title: "Lower Body Hip & Ankle Opener",
    type: "warmup",
    durationMinutes: 8,
    targetArea: "Lower Body",
    exercises: [
      { name: "World's Greatest Stretch", durationOrReps: "5 reps/side", cues: "Deep lunge with elbow inside ankle, then rotate thoracic spine toward ceiling." },
      { name: "Bodyweight Cossack Squats", durationOrReps: "8 reps/side", cues: "Shift weight laterally to open adductors and test ankle dorsiflexion." },
      { name: "Glute Bridges (Bilateral)", durationOrReps: "15 reps with 2s hold", cues: "Wake up gluteal motor units before squats or deadlifts." },
      { name: "Leg Swings (Front/Back & Lateral)", durationOrReps: "12 swings/leg", cues: "Loosen hip flexors and hamstrings dynamically." },
    ],
  },
  {
    id: "cooldown-fullbody",
    title: "Full Body Parasympathetic Cool-Down",
    type: "cooldown",
    durationMinutes: 6,
    targetArea: "Full Body",
    exercises: [
      { name: "Child's Pose with Lat Reach", durationOrReps: "60 seconds", cues: "Sit hips onto heels, extend arms forward, and take deep diaphragmatic breaths." },
      { name: "Pigeon Pose / Glute Stretch", durationOrReps: "45 seconds/side", cues: "Release piriformis and deep hip external rotators." },
      { name: "Doorway Pectoral Stretch", durationOrReps: "30 seconds/side", cues: "Gently open chest wall and anterior deltoids." },
      { name: "Standing Calf & Hamstring Fold", durationOrReps: "45 seconds", cues: "Let head hang heavy to decompress spinal erectors." },
    ],
  },
];
